### ISSUE TITLE
Command line to upload a private package

### ISSUE THREAD

**Issue by ovz** [Binstar/docs.binstar.org#56]
How do I specify in binstar upload command line that my package shall be Private rather than public. Having 

binstar_personal: True

in .conda_rc doesn't seem to make this effect.

**Comment by srossross** [comment]
@ovz you must create a private package *namespace* before you upload your first file.

```
binstar package --create --private ovz/package
binstar upload -u ovz /path/to/package.bz2
```

If the package already exists on binstar.org then you will need to change this in the package settings via your browser.
